version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: benguino
      POSTGRES_PASSWORD: <set-from-dotenv-or-secret-manager>
      POSTGRES_DB: inventory_management
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
